---
- name: Install Apache
  hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install Apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: Start Apache2
      service: name=apache2 state=started enabled=yes

    - name: Set timezone to Africa/Lagos
      command: timedatectl set-timezone Africa/Lagos
      register: timezone_set

    - name: Input in index.html
      shell: echo "<h1>This is $(hostname) and the date is $(date)</h1>" | sudo tee /var/www/html/index.html
